### ISSUE TITLE
Question: why CEF format rather than syslog?

### ISSUE THREAD

**Issue by aremai** [Graylog2/graylog-guide-ossec#2]
Hi @lennartkoopmann ,

I appreciate your documentation on how to get OSSEC related events into Graylog. It's really good and works well.
However, I was wondering why you picked the CEF format for forwarding the events rather than normal Syslog?
is there any advantage for this?

cheers,
theresa

**Comment by lennartkoopmann** [comment]
Hi,

I picked CEF because of its structured nature that does not require custom parsing by the user. The alternative is to send syslog and parse out the information using the Graylog processing pipelines.

Hope that helps!

Cheers,
Lennnart
